import nodemailer from 'nodemailer';
import { config } from '../config';
import { generateInvoicePdf } from './pdf.service';

const transporter = nodemailer.createTransport({
  host: config.smtp.host,
  port: config.smtp.port,
  secure: config.smtp.port === 465,
  auth: {
    user: config.smtp.user,
    pass: config.smtp.pass,
  },
});

interface InvoiceEmailData {
  invoiceNumber: string;
  issueDate: Date;
  dueDate: Date;
  subtotal: any;
  taxRate: any;
  taxAmount: any;
  total: any;
  notes: string | null;
  client: {
    name: string;
    email: string;
    address: string | null;
    phone: string | null;
  };
  user: {
    name: string;
    companyName: string | null;
    address?: string | null;
    email: string;
    phone?: string | null;
  };
  items: Array<{
    description: string;
    quantity: any;
    unitPrice: any;
    total: any;
  }>;
}

export async function sendInvoiceEmail(invoice: InvoiceEmailData): Promise<void> {
  const pdfBuffer = await generateInvoicePdf(invoice);
  const companyName = invoice.user.companyName || invoice.user.name;

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: #4F46E5; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; background: #f9f9f9; }
        .footer { text-align: center; padding: 20px; font-size: 12px; color: #666; }
        .amount { font-size: 24px; font-weight: bold; color: #4F46E5; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>Invoice ${invoice.invoiceNumber}</h1>
        </div>
        <div class="content">
          <p>Dear ${invoice.client.name},</p>
          <p>Please find attached invoice <strong>${invoice.invoiceNumber}</strong> from ${companyName}.</p>
          <p class="amount">Total Amount: $${Number(invoice.total).toFixed(2)}</p>
          <p><strong>Due Date:</strong> ${new Date(invoice.dueDate).toLocaleDateString()}</p>
          <p>If you have any questions about this invoice, please don't hesitate to contact us.</p>
          <p>Thank you for your business!</p>
          <p>Best regards,<br>${companyName}</p>
        </div>
        <div class="footer">
          <p>This invoice was generated by Invoice App</p>
        </div>
      </div>
    </body>
    </html>
  `;

  await transporter.sendMail({
    from: config.smtp.from,
    to: invoice.client.email,
    subject: `Invoice ${invoice.invoiceNumber} from ${companyName}`,
    html: htmlContent,
    attachments: [
      {
        filename: `${invoice.invoiceNumber}.pdf`,
        content: pdfBuffer,
        contentType: 'application/pdf',
      },
    ],
  });
}

interface ReminderEmailData {
  invoiceNumber: string;
  dueDate: Date;
  total: any;
  client: {
    name: string;
    email: string;
  };
  user: {
    name: string;
    companyName: string | null;
    email: string;
  };
}

export async function sendReminderEmail(invoice: ReminderEmailData): Promise<void> {
  const companyName = invoice.user.companyName || invoice.user.name;
  const isOverdue = new Date(invoice.dueDate) < new Date();

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: ${isOverdue ? '#DC2626' : '#F59E0B'}; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; background: #f9f9f9; }
        .footer { text-align: center; padding: 20px; font-size: 12px; color: #666; }
        .amount { font-size: 24px; font-weight: bold; color: ${isOverdue ? '#DC2626' : '#F59E0B'}; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>${isOverdue ? 'Overdue' : 'Payment'} Reminder</h1>
        </div>
        <div class="content">
          <p>Dear ${invoice.client.name},</p>
          <p>This is a friendly reminder that invoice <strong>${invoice.invoiceNumber}</strong> ${isOverdue ? 'was due on' : 'is due on'} <strong>${new Date(invoice.dueDate).toLocaleDateString()}</strong>.</p>
          <p class="amount">Amount Due: $${Number(invoice.total).toFixed(2)}</p>
          ${isOverdue ? '<p><strong>This invoice is now overdue.</strong> Please make payment at your earliest convenience.</p>' : '<p>Please ensure payment is made by the due date.</p>'}
          <p>If you have already made the payment, please disregard this reminder.</p>
          <p>If you have any questions, please contact us.</p>
          <p>Best regards,<br>${companyName}</p>
        </div>
        <div class="footer">
          <p>This reminder was sent by Invoice App</p>
        </div>
      </div>
    </body>
    </html>
  `;

  await transporter.sendMail({
    from: config.smtp.from,
    to: invoice.client.email,
    subject: `${isOverdue ? 'Overdue' : 'Payment'} Reminder: Invoice ${invoice.invoiceNumber}`,
    html: htmlContent,
  });
}
